"""initial_schema_with_json_and_postgres_types

Revision ID: 8842c3c0d9db
Revises: 
Create Date: 2026-08-21 00:53:51.995900

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8842c3c0d9db'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('audit_logs', 'details',
               existing_type=sa.TEXT(),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('evidence', 'provenance_detail',
               existing_type=sa.TEXT(),
               type_=sa.JSON(),
               existing_nullable=False)
    op.alter_column('findings', 'related_evidence_ids',
               existing_type=sa.TEXT(),
               type_=sa.JSON(),
               existing_nullable=False)
    op.alter_column('findings', 'related_relationship_ids',
               existing_type=sa.TEXT(),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('findings', 'parameters_used',
               existing_type=sa.TEXT(),
               type_=sa.JSON(),
               existing_nullable=False)
    op.alter_column('report_pages', 'tables_json',
               existing_type=sa.TEXT(),
               type_=sa.JSON(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('report_pages', 'tables_json',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('findings', 'parameters_used',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('findings', 'related_relationship_ids',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('findings', 'related_evidence_ids',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('evidence', 'provenance_detail',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('audit_logs', 'details',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               existing_nullable=True)
    # ### end Alembic commands ###
