import os
import logging
import requests
from typing import Dict, Any, Optional
from app.core.config import settings

logger = logging.getLogger(__name__)

GROQ_MODEL = settings.GROQ_MODEL or "openai/gpt-oss-20b"
GROQ_API_URL = "https://api.groq.com/openai/v1/chat/completions"


class ExternalLLMNotConfiguredError(Exception):
    """Raised when external LLM query is requested but API key is not configured."""
    pass


class ExternalLLMError(Exception):
    """Raised when external LLM service returns an error or is unavailable."""
    pass


class ExternalLLMTimeoutError(Exception):
    """Raised when external LLM service times out during generation."""
    pass


class ExternalLLMClient:
    """
    Client for Groq's hosted OpenAI-compatible chat completions API.
    
    SAFETY ENFORCEMENT GUARANTEE:
    Structurally incapable of accepting raw RetrievalResult objects or unminimized evidence.
    Accepts ONLY minimized dictionary payloads generated by `minimize_for_external()`.
    """

    def __init__(
        self,
        api_key: Optional[str] = None,
        model: Optional[str] = None,
        provider: str = "groq"
    ):
        self._api_key = api_key
        self._model = model
        self.provider = provider

    @property
    def api_key(self) -> str:
        return self._api_key or settings.EXTERNAL_LLM_API_KEY or os.getenv("EXTERNAL_LLM_API_KEY", "")

    @property
    def model(self) -> str:
        return self._model or settings.GROQ_MODEL or os.getenv("GROQ_MODEL", "openai/gpt-oss-20b")

    def generate_external_answer(self, minimized_payload: Dict[str, Any], timeout_seconds: int = 30) -> str:
        """
        Sends ONLY minimized/pseudonymized data payload to Groq's OpenAI-compatible API.
        """
        # Strict Type & Privacy Signature Enforcement
        if not isinstance(minimized_payload, dict):
            raise TypeError("ExternalLLMClient accepts ONLY dict payloads. Passing raw objects is strictly prohibited.")

        if minimized_payload.get("privacy_level") != "MINIMIZED_PSEUDONYMIZED":
            raise TypeError(
                "ExternalLLMClient rejected payload: Missing mandatory 'MINIMIZED_PSEUDONYMIZED' privacy level token."
            )

        key = self.api_key
        if not key or not key.strip():
            logger.error("External LLM requested but EXTERNAL_LLM_API_KEY is not configured.")
            raise ExternalLLMNotConfiguredError(
                "External LLM is not configured. EXTERNAL_LLM_API_KEY is missing. "
                "Please set EXTERNAL_LLM_API_KEY (Groq API key from console.groq.com) or select llm_provider='local'."
            )

        logger.info(f"Sending minimized pseudonymized payload to Groq model '{self.model}'...")

        # Construct grounded prompt from top minimized elements (sliced to fit context window)
        question = minimized_payload.get("original_question", "")
        report_id = minimized_payload.get("report_id", "")
        ev_items = minimized_payload.get("evidence", [])[:20]
        rel_items = minimized_payload.get("relationships", [])[:25]
        fnd_items = minimized_payload.get("findings", [])[:15]
        tl_items = minimized_payload.get("timeline_entries", [])[:15]

        evidence_lines = []
        if ev_items:
            evidence_lines.append("--- MINIMIZED EVIDENCE ITEMS ---")
            for e in ev_items:
                evidence_lines.append(f"- ID: [{e.get('evidence_id')}] | Type: {e.get('evidence_type')} | Value: '{e.get('value')}' | Confidence: {e.get('confidence')}")

        if rel_items:
            evidence_lines.append("\n--- MINIMIZED DERIVED RELATIONSHIPS ---")
            for r in rel_items:
                evidence_lines.append(f"- ID: [{r.get('id')}] | Triplet: ({r.get('source_value')}) --[{r.get('relationship_type')}]--> ({r.get('target_value')}) | Class: {r.get('classification')} | Rule: {r.get('rule_id')} | Explanation: {r.get('explanation')}")

        if fnd_items:
            evidence_lines.append("\n--- MINIMIZED FLAGGED FINDINGS ---")
            for f in fnd_items:
                evidence_lines.append(f"- ID: [{f.get('id')}] | Finding: {f.get('rule_name')} ({f.get('severity')} Severity) | Explanation: {f.get('explanation')} | Evidence Linked: {f.get('related_evidence_ids')}")

        if tl_items:
            evidence_lines.append("\n--- MINIMIZED TIMELINE EVENTS ---")
            for t in tl_items:
                evidence_lines.append(f"- Timestamp: {t.get('timestamp')} | Title: {t.get('title')} | Class: {t.get('classification')} | Entry ID: {t.get('entry_id')}")

        evidence_text = "\n".join(evidence_lines) if evidence_lines else "NO EVIDENCE RECORDED."

        system_instruction = (
            "You are an official AI Forensic Assistant for the Ministry of Home Affairs (India) analyzing UFDR reports. "
            "STRICT RULES:\n"
            "1. Answer ONLY using the provided evidence block.\n"
            "2. CITATION MANDATE: Every claim MUST include bracketed evidence citations like [EVT-XXXX], [REL-XXXX], or [FND-XXXX].\n"
            "3. ZERO HALLUCINATION: Never invent names, numbers, or events not in the evidence.\n"
            "4. If evidence is insufficient, state explicitly what is missing."
        )

        user_prompt = f"""--- EVIDENCE BLOCK ---
Report ID: {report_id}
{evidence_text}

--- INVESTIGATOR QUESTION ---
"{question}"

--- ASSISTANT GROUNDED RESPONSE ---
"""

        headers = {
            "Authorization": f"Bearer {key.strip()}",
            "Content-Type": "application/json",
        }
        payload = {
            "model": self.model,
            "messages": [
                {"role": "system", "content": system_instruction},
                {"role": "user", "content": user_prompt},
            ],
            "temperature": 0.1,
        }

        try:
            response = requests.post(GROQ_API_URL, headers=headers, json=payload, timeout=timeout_seconds)
            if response.status_code in [401, 403]:
                raise ExternalLLMNotConfiguredError(
                    f"External LLM (Groq) authentication failed ({response.status_code}). Invalid or expired EXTERNAL_LLM_API_KEY."
                )
            if response.status_code >= 400:
                raise ExternalLLMError(
                    f"External LLM (Groq) temporarily unavailable ({response.status_code}): {response.text[:200]}"
                )

            res_json = response.json()
            choices = res_json.get("choices", [])
            if not choices:
                raise ExternalLLMError("External LLM (Groq) returned an empty choice response.")

            answer_text = choices[0].get("message", {}).get("content", "").strip()
            return answer_text

        except requests.exceptions.Timeout as te:
            logger.error(f"Groq API request timed out after {timeout_seconds}s: {te}")
            raise ExternalLLMTimeoutError(f"External LLM (Groq) request timed out after {timeout_seconds} seconds.") from te
        except (ExternalLLMNotConfiguredError, ExternalLLMError, ExternalLLMTimeoutError):
            raise
        except Exception as e:
            logger.error(f"Groq API call error: {e}")
            raise ExternalLLMError(f"External LLM (Groq) temporarily unavailable: {str(e)}") from e
